# metadata specialised for each experiment
core:
  project_name: radar-multipath-classification
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: 0.0.1
  tags: null

radar:
  near_sector:
    range: 85
    azi: 60
  far_sector:
    range: 250
    azi: 9

defaults:
  - hydra: default
  - nn: default
  - train: default
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
